/* Smack C++ @ https://github.com/smacklib/dev_smack_cpp
 *
 * Definition of the Locale class.
 *
 * Copyright © 2019-2026 Michael Binz
 */

#pragma once

#include <mutex>
#include <optional>
#include <map>
#include <string>
#include <string_view>

#include "smack_util.hpp"

namespace smack {

/**
 * A simplified locale consisting of a country and a language code.
 * The language code is optional.
 *
 * It is recommended to use the ISO 639-1 two-letter language code and the
 * ISO 3166-1 two-letter country code.  This is not required, any different
 * language or country  code is allowed as long as this is used in the
 * naming of the resouce bundles.
 *
 * Language and country codes must not contain the '_' character.
 *
 * External notation as generated by the \b toString operation is
 * 'language_country', if no country is given only 'language'.
 * If neither language nor country is given, the empty string is returned.
 */
class Locale final {

    /**
     * The locale's language.
     */
    std::string language_;

    /**
     * The locale's country.  May be the empty string.
     */
    std::string country_;

    /**
     * The currently set locale.
     */
    static std::optional<Locale> current_;

    /**
     * A mutex for the current_ member.
     */
    static inline std::mutex current_mutex_;

public:
    /**
     * Creates a locale from a name.  The name is expected to be in the format
     * 'language_country' or 'language'.  The '_' character is used as separator.
     *
     * Returns the empty locale if the passed name is empty.
     */
    static auto makeLocaleFromName(const std::string& name) -> Locale;

    /**
     * Creates a default locale with an empty country and language.
     */
    Locale();

    /**
     * Create an instance.
     *
     * @param isoLanguage The iso language code.
     * @param isoCountry The iso country code.  Defaults to the empty string.
     * @throws std::invalid_argument If isoLanguage is the empty string, or if
     * isoCountry or isoLanguage contain the '_'-character.
     */
    Locale(std::string_view isoLanguage, std::string_view isoCountry = "");

    ~Locale() = default;

    /**
     * Check if the locale is empty, i.e. both language and country are empty.
     */
    auto isEmpty() const -> bool;

    /**
     * Get the Locale-name properly concatenated.  The order is
     * language[_country].
     * Example 'de_DE' or 'de'.
     *
     * The default locale is the empty string.
     */
    auto toString() const -> std::string;

    /**
     * Get the country.  For the fallback locale this may be the empty
     * string.
     */
    auto getCountry() const -> std::string;

    /**
     * Get the language. May be the empty string if none is set.
     */
    auto getLanguage() const -> std::string;

    /**
     * Get the parent locale.  If the current locale has no country,
     * the parent is empty.
     */
    auto getParent() const -> Locale;

    /**
     * Get the currently active locale.  If the current locale has not been
     * set, then the system locale is returned.
     */
    static auto getCurrent() -> Locale;

    /**
     * Set the currently active locale.  This is intended as the interface
     * to a system that knows the current locale and can set it properly.
     *
     * Returns the previously set locale.  This is the system locale if
     * the current locale has not been set before.
     */
    static auto setCurrent(const Locale& locale) -> Locale;

    /**
     * Support std::map<Locale>.
     */
    bool operator<(const Locale& r) const;

    /**
     * Support std::set<Locale>.
     */
    bool operator==(const Locale& r) const;
};

} // namespace smack
