/* Smack C++ @ https://github.com/smacklib/dev_smack_cpp
 *
 * Definition of the Locale class.
 *
 * Copyright © 2019-2026 Michael Binz
 */

#pragma once

#include <memory>
#include <mutex>
#include <optional>
#include <stdexcept>
#include <map>
#include <iomanip>
#include <sstream>
#include <string>
#include <string_view>
#include <type_traits>

#include "smack_convert.hpp"
#include "smack_util.hpp"

namespace smack::localisation {

/**
 * A simplified locale consisting of a country and a language code.
 * The language code is optional.
 *
 * It is recommended to use the ISO 639-1 two-letter language code and the
 * ISO 3166-1 two-letter country code.  This is not required, any different
 * language or country  code is allowed as long as this is used in the
 * naming of the resouce bundles.
 *
 * Language and country codes must not contain the '_' character.
 *
 * External notation as generated by the \b toString operation is
 * 'language_country', if no country is given only 'language'.
 */
class Locale final {

    /**
     * The locale's language.
     */
    std::string language_;

    /**
     * The locale's country.  May be the empty string.
     */
    std::string country_;

    /**
     * The currently set locale.
     */
    static std::optional<Locale> current_;

    /**
     * A mutex for the current_ member.
     */
    static inline std::mutex current_mutex_;

public:
/**
 * Creates a locale from a name.  The name is expected to be in the format
 * 'language_country' or 'language'.  The '_' character is used as separator.
 *
 * Returns the empty locale if the passed name is empty.
 */
    static auto makeLocaleFromName(const std::string& name) -> Locale
    {
        if ( name.empty() ) {
            return Locale{};
        }

        auto parts = smack::split(name, "_");

        if (parts.size() == 1) {
            return Locale{parts[0]};
        }
        if (parts.size() == 2) {
            return Locale{parts[0], parts[1]};
        }

        throw std::invalid_argument("Invalid locale name: " + name);
    }

    /**
     * Creates a default locale with an empty country and language.
     */
    Locale()
    {
    }

    /**
     * Create an instance.
     *
     * @param isoLanguage The iso language code.
     * @param isoCountry The iso country code.  Defaults to the empty string.
     * @throws std::invalid_argument If isoLanguage is the empty string, or if
     * isoCountry or isoLanguage contain the '_'-character.
     */
    Locale(std::string_view isoLanguage, std::string_view isoCountry = "")
        : language_{isoLanguage}
        , country_{isoCountry}
    {
        if (country_.find_first_of("_") != std::string::npos) {
            throw std::invalid_argument("isoCountry contains '_'.");
        }
        if (language_.find_first_of("_") != std::string::npos) {
            throw std::invalid_argument("isoLanguage contains '_'.");
        }
    }

    ~Locale() = default;

    /**
     * Check if the locale is empty, i.e. both language and country are empty.
     */
    auto isEmpty() const -> bool
    {
        return language_.empty() && country_.empty();
    }

    /**
     * Get the Locale-name properly concatenated.  The order is
     * language[_country].
     * Example 'de_DE' or 'de'.
     */
    auto toString() const -> std::string
    {
        if (country_.empty()) {
            return language_;
        }

        return language_ + "_" + country_;
    }

    /**
     * Get the country.  For the fallback locale this may be the empty
     * string.
     */
    auto getCountry() const -> std::string
    {
        return country_;
    }

    /**
     * Get the language. May be the empty string if none is set.
     */
    auto getLanguage() const -> std::string
    {
        return language_;
    }

    /**
     * Get the parent locale.  If the current locale has no country,
     * the parent is empty.
     */
    auto getParent() const -> Locale
    {
        if (country_.empty()) {
            return Locale{};
        }

        return Locale{language_};
    }

    /**
     * Get the currently active locale.  If the current locale has not been
     * set, then the system locale is returned.
     */
    static auto getCurrent() -> Locale
    {
        std::lock_guard<std::mutex> _(current_mutex_);

        if (!current_.has_value())
            current_ = smack::system::getLocale();

        return current_.value();
    }

    /**
     * Set the currently active locale.  This is intended as the interface
     * to a system that knows the current locale and can set it properly.
     *
     * Returns the previously set locale.  This is the system locale if
     * the current locale has not been set before.
     */
    static auto setCurrent(const Locale& locale) -> Locale
    {
        auto result = getCurrent();

        std::lock_guard<std::mutex> _(current_mutex_);

        current_ = locale;

        return result;
    }

    /**
     * Support std::map<Locale>.
     */
    bool operator<(const Locale& r) const
    {
        return toString() < r.toString();
    }

    /**
     * Support std::set<Locale>.
     */
    bool operator==(const Locale& r) const
    {
        return toString() == r.toString();
    }
};

} // namespace smack::localisation
